rogpeppe/go-internal

- goproxytest/proxy.go
- gotooltest/setup.go
- imports/build.go
- imports/read.go
- imports/read_test.go
- imports/scan.go
- imports/scan_test.go
- imports/testdata/import1/x.go
- imports/testdata/import1/x1.go
- imports/testdata/import1/x_darwin.go
- imports/testdata/import1/x_windows.go
- testscript/cmd.go
- testscript/testscript.go
This package sets up the testscript parameters
to add support for the go command and related conditions.
I've removed support for running Go binaries because
there's quite a bit of complexity in the original there and I don't need
to do that yet.
This also needs the imports package to get the supported architectures
and OS's, so we pull that in too.
> gotooltest: support the go command in script tests

- go.mod
- go.sum
- testscript/cmd.go
- testscript/exe.go
- testscript/testscript.go
- testscript/testscript_test.go
Also change the API so that we use RunMain not RegisterCommand,
as that makes it possible to merge the test coverage at the end of the
test run.
> implement support for coverage

- testscript/cover.go
- testscript/exe.go
Instead of just concatenating all the coverage files, we merge them as they're generated. We use the same struct that's used in testing for coverage tracking. This may break of course as that type (or in fact very little of what we're doing here) is covered the the Go compatibility guarantee. What fun!
This also makes it easy to print information about the final coverage level (although we can't avoid the original message).
The profile parsing code was adapted directly from `src/cmd/cover/profile.go` at v1.11.
> testscript: better coverage support

- .travis.yml
- README.md
- cmd/txtar-addmod/addmod.go
- cmd/txtar-goproxy/main.go
- cmd/txtar-savedir/savedir.go
- go.mod
- goproxytest/proxy.go
- goproxytest/pseudo.go
- gotooltest/setup.go
- imports/scan_test.go
- modfile/rule.go
- module/module.go
- testscript/cmd.go
- testscript/doc.go
- testscript/testscript.go
It's really more than modinternal (e.g. testscript isn't related to modules).
> rename repository to go-internal

- cmd/txtar-goproxy/main.go
- goproxytest/proxy.go
If we import the testing package, we pollute the txtar-goproxy
command's usage with all the testing flags, which are not
relevant, so avoid doing that. We might need to add
the capability to toggle verbose messages later.
> goproxytest: avoid import of testing package

- testscript/exe.go
Making it compile under earlier versions than 1.10 is a bit
harder, so punt for now.
> testscript: make it compile under Go 1.10

- testscript/cmd.go
- testscript/doc.go
Originally added in https://go-review.googlesource.com/c/147277
> testscript: add cmpenv command to testing script language

- testscript/doc.go
- testscript/testscript.go
Originally added in https://go-review.googlesource.com/c/147280
> testscript: add goversion environment variable to testing script language

- cmd/txtar-addmod/addmod.go
- cmd/txtar-addmod/testdata/encode.txt
- cmd/txtar-addmod/testdata/mod/github.com_shurcoo!l_httpfs_v0.0.0-20171119174359-809beceb2371.txt
The URL we fetch with txtar-addmod needs to contain a regular path.
The path on disk however, must be the special ! encoded path.
> cmd/txtar-addmod: fix bug resolving directory path in module cache.

- testscript/cmd.go
- testscript/scripts/setenv.txt
- testscript/testscript.go
- testscript/testscript_test.go
Allows environment variables to be set by Run-Param commands.
> testscript: add *TestScript.Setenv method

- cmd/txtar-addmod/addmod.go
- cmd/txtar-addmod/testdata/mod/github.com_gobin-testrepos_simple-main_v1.0.0.txt
- cmd/txtar-addmod/testdata/txtar-addmod-self.txt
This can be useful if certain extra files are needed to pass some tests,
for example.
Added a simple test case too.
Fixes #28.
> cmd/txtar-addmod: -all flag to include all files

- cmd/txtar-savedir/savedir.go
- cmd/txtar-savedir/script_test.go
- cmd/txtar-x/extract.go
- cmd/txtar-x/extract_test.go
- cmd/txtar-x/testdata/extract-dir.txt
- cmd/txtar-x/testdata/extract-out-of-bounds.txt
- cmd/txtar-x/testdata/extract-stdin.txt
- cmd/txtar-x/testdata/extract.txt
- testscript/cmd.go
- testscript/doc.go
- testscript/scripts/stdin.txt
- testscript/testscript.go
This allows the easy extraction of files from a txtar file on the command line.
Also add functionality to testscript to make it possible to set up the standard
input of an execed command.
> cmd/txtar-x: new command

- .travis.yml
- gotooltest/script_test.go
- gotooltest/setup.go
- gotooltest/testdata/version.txt
- testscript/testscript.go
This effectively mirrors the go/build constraint supports such as go1.12
to check that the Go version is >= 1.12.
Also remove some duplicated code in testscript that I had previously
missed was already present in gotooltest.
> gotooltest: add support for version constraints

- gotooltest/setup.go
- gotooltest/testdata/version.txt
- testscript/exe.go
- testscript/scripts/interrupt.txt
- testscript/testscript.go
- testscript/testscript_test.go
This adds a method to TestScript to provide access to the
commands that have been started in the background.
This enables use cases like testing signal handling in
commands.
We also move the OS and architecture conditions to
the base testscript package so that scripts can get
access to OS conditions without importing gotooltest.
> testscript: provide access to background commands

- cmd/testscript/main.go
- cmd/testscript/testdata/noproxy.txt
- cmd/testscript/testdata/simple.txt
- gotooltest/setup.go
This can make tests that use the go command
considerably faster. We override GOPROXY when
we're running a local Go test proxy.
> gotooltest: pass through GOPROXY

- internal/os/execpath/exec.go
- internal/os/execpath/lp_js.go
- internal/os/execpath/lp_plan9.go
- internal/os/execpath/lp_unix.go
- internal/os/execpath/lp_windows.go
- testscript/cmd.go
- testscript/envvarname.go
- testscript/envvarname_windows.go
- testscript/scripts/exec_path_change.txt
- testscript/scripts/execguard.txt
- testscript/testscript.go
Includes a partial snapshot of os/exec's platform-specific LookPath
logic, as of 0456036e28b718d215f49abe83d3c49101f8a4c7. This is largely a
copy and paste, with a type alias to os/exec.Error and an "alias" of
os/exec.ErrNotFound.
> testscript: respect TestScript env PATH variable for exec command

- testscript/testdata/setupfiles.txt
- testscript/testscript.go
- testscript/testscript_test.go
This allows a setup step to see the unarchived files
(for example we can use this to start a go module
proxy server in Setup that serves modules from the
testscript contents).
> testscript: let Setup see unarchived txtar files

- testscript/cmd.go
- testscript/doc.go
- testscript/testdata/cpstdout.txt
Cherry picked from https://go-review.googlesource.com/c/163519
> testscript: allow "stdout" and "stderr" as inputs to script_test "cp" command

- cmd/testscript/main_test.go
- cmd/txtar-savedir/savedir.go
- cmd/txtar-savedir/testdata/needquote.txt
- cmd/txtar-savedir/testdata/quote.txt
- cmd/txtar-savedir/testdata/txtar-savedir-self.txt
- testscript/cmd.go
- testscript/doc.go
- txtar/archive.go
- txtar/archive_test.go
We add an unquote command to the standard set of commands,
because it's not that uncommon a requirement.
We add a `-quote` flag to txtar-savedir that will automatically
quote files if needed, adding an unquote command to the
comment section.
Future work could add a way of quoting arbitrary data (e.g. binary
data) but this should do for now.
Fixes #11.
> testscript: add unquote command

- cmd/txtar-c/savedir.go
- cmd/txtar-c/script_test.go
- cmd/txtar-c/testdata/all.txt
- cmd/txtar-c/testdata/needquote.txt
- cmd/txtar-c/testdata/quote.txt
- cmd/txtar-c/testdata/txtar-savedir-self.txt
- goproxytest/proxy.go
I could never remember the txtar-savedir name and `txtar-c` seems more
reminiscent of the `tar` original.
Also it's sometimes useful to be able to create txtar files containing
dot files (particularly `.gomodproxy` directories) so allow that too.
> cmd/txtar-savedir: add -a flag and rename to txtar-c

- cmd/txtar-addmod/addmod.go
- cmd/txtar-addmod/testdata/to_stdout.txt
This makes it easier to produce inline module definitions for
inclusion in txtar files.
> cmd/txtar-addmod: allow stdout destination

- testscript/testdata/exec_path_change.txt
- testscript/testdata/values.txt
- testscript/testscript.go
- testscript/testscript_test.go
Currently, if Setup sets up something, there's no way for it
to pass values through to custom commands other than
strings (with Setenv). To allow this, we add a map of
arbitrary values to Env that can be accessed by custom commands.
Like context.Context, the keys are `interface{}` values to
allow external helper libraries to add their own keys without
fear of clashing with others.
> testscript: provide way for Setup to pass values to commands

- fmtsort/export_test.go
- fmtsort/mapelem.go
- fmtsort/mapelem_1.11.go
- fmtsort/sort.go
- fmtsort/sort_test.go
It's not uncommon to want this when pretty-printing Go values.
> fmtsort: copy from stdlib

- .travis.yml
- cmd/testscript/main.go
- cmd/testscript/main_test.go
- cmd/testscript/testdata/env_var_with_go.txt
- cmd/txtar-addmod/script_test.go
- go.mod
- goproxytest/proxy.go
- goproxytest/proxy_test.go
- goproxytest/testdata/list.txt
- testscript/testscript_test.go
Also:
* make explicit the entire Go version matrix
* make goproxytest honour the 404 behaviour expected by cmd/go in tip as
a result of https://go-review.googlesource.com/c/go/+/189517
> ci: changes for go1.13beta1

- testscript/testdata/evalsymlink.txt
- testscript/testscript.go
I ran into issues in `govim` with the testscript matcher since it uses real paths in the logs. When running macOS `ioutil.TempDir()` returns a sym-linked directory by default.
This PR ensures that the path used is a real directory by evaluating the root test temp dir that acts as base for `$WORK`.
See full description in https://github.com/myitcv/govim/issues/308
> testscript: ensure that temp dir isn't a symlink

- .travis.yml
PR sets the Go version to `1.13` since it is released now.
> change 1.13beta1 to 1.13

- testscript/cmd.go
- testscript/testdata/readfile.txt
- testscript/testscript.go
- testscript/testscript_test.go
This allows custom commands to operate on the output of previous
exec commands similar to the built in cp and cmp commands.
> testscript: add ReadFile method

- testscript/cmd.go
- testscript/testdata/testscript_update_script.txt
- testscript/testdata/testscript_update_script_not_in_archive.txt
- testscript/testdata/testscript_update_script_quote.txt
- testscript/testdata/testscript_update_script_stderr.txt
- testscript/testscript.go
- testscript/testscript_test.go
This makes it possible for a test to automatically update the test scripts
when output changes. Does not cover `cmpenv`.
> testscript: implement UpdateScripts parameter

- testscript/testscript.go
- testscript/testscript_test.go
This can happen when either the Dir does not exist, or it is empty.
> testscript: fail a test when a testscript Dir contains no scripts

- testscript/testscript.go
- testscript/testscript_test.go
This way, the setup function could fail in case setting up the test is currently not possible.
Moreover, client code could type assert the returned testscript.T at its own risk, for instance for registering cleanup functions or using test helpers like
```go
tb := env.T().(testing.TB)
c := qt.New(tb)
env.Defer(c.Done)
```
> testscript: expose current subtest in Env

- testscript/cmd.go
- testscript/doc.go
- testscript/testdata/stdin.txt
Support these special files in the stdin, unquote, and match (grep)
commands. This is particularly useful to "pipe" output like "stdin
stdout", or to use commands that produce txtar output.
The grep one isn't super useful, as one can already do "stdout xxx"
instead of "grep xxx stdout", but this way it's more consistent and we
save some repeated lines. Because the feature is itself a bit redundant,
don't document it, to prevent confusing the user.
> testscript: support stdout/stderr in more builtins

- testscript/testscript.go
- testscript/testscript_test.go
Manipulating `Env.Vars` is not completely trivial: you need to handle last-entry-wins, invalid entries, and key normalization.
This PR adds `Getenv`, `LookupEnv`, and `Setenv` method to `Env` that function identically to their counterparts in the standard `os` package.
Example use:
```go
func TestFoo(t *testing.T) {
testscript.Run(t, testscript.Params{
Dir: "testdata",
Setup: func(e *Env) error {
e.Setenv("HOME", "/home/user")
e.Setenv("PATH", "/home/user/bin:" + e.Getenv("PATH"))
},
})
}
```
> testscript: add env convenience functions

- testscript/testdata/exec_path_change.txt
- testscript/testdata/stdin.txt
- testscript/testscript.go
${:} expands to os.PathListSeparator; now ${/} expands to
os.PathSeparator.
It's useful to skip windows-vs-unixy conditions, like the ones that we
simplified in exec_path_change with HOME and PATH.
It's also useful so that 'cmpenv stdout stdout.golden' can easily
support output which contains relative file paths.
While at it, make the stdin and exec_path_change scripts work on Wine
(i.e. vanilla Windows), which has neither Go nor coreutils installed.
> testscript: add ${/} as a companion to ${:}

- lockedfile/internal/filelock/filelock_fcntl.go
- lockedfile/lockedfile_test.go
Apply upstream CL 222277 per @bcmills
Automatically applied via:
(command cd /path/to/go; git diff c6f678b6efd6622d335e6d4b659282bb2d16f5ba~1 c6f678b6efd6622d335e6d4b659282bb2d16f5ba) | git apply -p5
with a minor fix to then use github.com/rogpeppe/go-internal/testenv
instead of internal/testenv
Fixes #91
> lockedfile: use a retry loop to suppress EDEADLK on AIX and Solaris

- testscript/cmd.go
- testscript/testdata/testscript_update_script_actual_is_file.txt
- testscript/testdata/testscript_update_script_expected_not_in_archive.txt
- testscript/testscript.go
There are currently constraints on the actual source for a failed cmp
comparison when Params.UpdateScripts is true: the actual must be either
stdout or stderr.
However it's unclear why this constraint is necessary.
Indeed it's a painful constraint when the actual source in a comparison
is file written by a previous command.
Relax this constraint because, after discussion with @mvdan
and @rogpeppe, we believe it safe to do so.
Add a test for this new logic where the actual is a file that is part of
the archive.
> testscript: relax constraints around actual source in cmp with update

- testscript/cmd.go
- testscript/doc.go
This pulls in the latest changes to `chmod` from upstream, as [requested by @myitcv](https://github.com/rogpeppe/go-internal/pull/102#issuecomment-629023974).
Note that this change breaks backwards compatibility. Upstream parses the permission as a regular integer, whereas testscript parses it as an octal integer, meaning that you need update your scripts to prefix permissions with a `0`.
Replaces #102.
> testscript: update chmod from golang/go

- fmtsort/mapelem.go
- fmtsort/mapelem_1.11.go
Applied upstream CL 191197 to mapelem.go. Cannot fully port to 1.11,
since MapRange started to be supported in 1.12, but we can still avoid
an index out-of-bounds panic.
Fixes #108.
> fmtsort: don't out-of-bounds panic if there's a race condition

- .github/workflows/test.yml
Otherwise, in the case a PR is created from a branch that is pushed to
this repo, we create a workflow run for the PR and the branch itself.
> ci: only build the master branch on push

- cmd/testscript/README.md
- cmd/testscript/help.go
- cmd/testscript/main.go
- cmd/testscript/testdata/env_values.txt
The -e flag for testscript currently allows the caller to specify that
environment variables are inherited from the current environment.
However this falls when the current environment does not have a value
set and you need to set a specific value. For example:
GOBUILD=$(go env GOBUILD) testscript -e GOBUILD script.txt
Instead, allow -e to also specify a value:
testscript -e GOBUILD=$(go env GOBUILD) script.txt
which feels more fluent/natural.
> cmd/testscript: allow -e flag to pass env value

- .github/workflows/test.yml
Go 1.16 beta1 is released not too long ago. We should also build against it in the ci pipeline.
> ci: include upcoming go1.16 in build matrix

- cmd/testscript/main.go
- cmd/testscript/testdata/work.txt
Turns out that we were only printing the cmd/testscript created work
directory for an argument. We also need to print (and preserve) the
working directory that is created by testscript itself when running the
script.
Combine this with a bit of light refactoring to improve readability.
> cmd/testscript: make -work actually work

- testscript/testdata/testscript_update_script.txt
- testscript/testdata/testscript_update_script_actual_is_file.txt
- testscript/testdata/testscript_update_script_expected_not_in_archive.txt
- testscript/testdata/testscript_update_script_quote.txt
- testscript/testdata/testscript_update_script_stderr.txt
- testscript/testscript_test.go
This allows us to use testscript the meta command in non-update mode.
> testscript: rename testscript-update meta command to testscript

- gotooltest/testdata/cover.txt
The need for a real fix for this is captured in #130
> gotooltest: skip flakey test on darwin

- cmd/testscript/testdata/work.txt
- testscript/testdata/setupfiles.txt
- testscript/testscript.go
When running a testscript, we currently create a temporary directory in
$WORK/tmp. This is problematic because it interacts badly with cmd/go
(which is used by go/packages) trying to resolve the ./... pattern from
$WORK.
Instead establish a temporary directory in workdir, but use a prefix
that ensures this directory will not be walked when resolving the ./...
pattern from workdir.
> testscript: create a hidden temp directory by default

- cmd/testscript/testdata/simple.txt
- cmd/txtar-addmod/addmod.go
- gotooltest/setup.go
- gotooltest/testdata/env.txt
> Revert "gotooltest: proxy the new GOMODCACHE env var too"

- testscript/doc.go
The `cmd/testscript` flag is called `-work`, but the `testscript` flag is called `-testwork` so as to not conflict with the Go tool's own `-work` flag. Update the docs to reflect this.
> testscript: fix -testwork flag name in doc comments

- .github/workflows/test.yml
- cache/default_unix_test.go
- fmtsort/mapelem.go
- fmtsort/mapelem_1.11.go
- go.mod
- imports/testdata/import1/x1.go
- internal/os/execpath/lp_js.go
- internal/os/execpath/lp_unix.go
- internal/syscall/windows/registry/key.go
- internal/syscall/windows/registry/syscall.go
- internal/syscall/windows/registry/value.go
- lockedfile/internal/filelock/filelock_fcntl.go
- lockedfile/internal/filelock/filelock_other.go
- lockedfile/internal/filelock/filelock_plan9.go
- lockedfile/internal/filelock/filelock_test.go
- lockedfile/internal/filelock/filelock_unix.go
- lockedfile/internal/filelock/filelock_windows.go
- lockedfile/lockedfile_filelock.go
- lockedfile/lockedfile_plan9.go
- lockedfile/lockedfile_test.go
- testenv/testenv_cgo.go
- testenv/testenv_notwin.go
- testscript/envvarname.go
- testscript/exe.go
- testscript/exe_go118.go
- testscript/exe_pre_go1.18.go
> testscript: add support for Go master aka 1.18

- .github/workflows/test.yml
- testscript/exe_go118.go
> testscript: adapt to another Go 1.18 tip change

- cmd/testscript/main.go
- testscript/cmd.go
- testscript/testscript.go
- testscript/testscript_test.go
When a script has failed, the output of the commands running in the
background can be useful to see, so display it then and also in verbose
mode.
> testscript: print background command output on failure

- testscript/cmd.go
- testscript/doc.go
- testscript/testdata/wait.txt
- testscript/testscript.go
This lets us wait for an individual background command rather
than all of them at once.
> testscript: support named background commands

- go.mod
- go.sum
- testscript/cover.go
There's no need to use it and every dependency lost is good.
> testscript: remove errgo dependency

- gotooltest/setup.go
- testscript/doc.go
- testscript/testdata/cond.txt
- testscript/testscript.go
As suggested by @mvdan in https://github.com/rogpeppe/go-internal/pull/150#issuecomment-1055495507. Replaces #150.
> testscript: add Go compiler and version conditions

- cmd/testscript/testdata/env_var_with_go.txt
- goproxytest/testdata/list.txt
- gotooltest/setup.go
> gotooltest: move default GOPATH out of the main module

- .gitattributes
- cmd/testscript/README.md
- cmd/testscript/help.go
- cmd/testscript/main.go
- cmd/testscript/testdata/work.txt
- cmd/txtar-addmod/addmod.go
- cmd/txtar-addmod/testdata/encode.txt
- cmd/txtar-addmod/testdata/txtar-addmod-self.txt
- cmd/txtar-c/savedir.go
- goproxytest/proxy.go
- testscript/doc.go
- testscript/testdata/testscript_update_script.txt
- testscript/testscript.go
- testscript/testscript_test.go
(see commit message)
Fixes #126.
> all: add support for txtar extension and prefer it

- testscript/cmd.go
- testscript/exe.go
- testscript/testdata/testscript_explicit_exec.txt
- testscript/testscript.go
- testscript/testscript_test.go
(see commit message)
Fixes #163.
> testscript: add Params.RequireExplicitExec

- imports/build.go
- testscript/doc.go
- testscript/testdata/cond.txt
- testscript/testscript.go
(see commit messages)
Fixes #166.
> Add 'unix' condition

- testscript/exe.go
- testscript/testdata/testscript_explicit_exec.txt
> testscript: fix RequireExplicitExec error messages

- testscript/cmd.go
- testscript/doc.go
- testscript/exe.go
- testscript/testdata/cpstdout.txt
- testscript/testdata/testscript_explicit_exec.txt
(see commit message)
Fixes #153.
> testscript: port "mv" and "! cmp" from upstream

- cache/cache.go
- cache/cache_test.go
- cache/default.go
- cmd/testscript/main.go
- cmd/txtar-addmod/addmod.go
- cmd/txtar-x/extract_test.go
- dirhash/hash_test.go
- lockedfile/lockedfile.go
- lockedfile/lockedfile_test.go
- lockedfile/mutex.go
- testscript/cmd.go
- testscript/exe.go
- testscript/testscript.go
- testscript/testscript_test.go
- txtar/archive.go
Since Go 1.13, octal literals can be written using an `0o` prefix, instead of the (slightly) ambiguous `0`. Indeed, `gofumpt` insists on this, and those of us who use `gopls` with `gofumpt` enabled have our octal literals rewritten for us automatically.
This commit applies that change, along with some other minor `gofumpt`-age, including adding or removing blank lines and reformatting doc comments.
> Use 0o prefix for octal literals, and `gofumpt` all files

- testscript/testdata/big_diff.txt
- testscript/testdata/long_diff.txt
- testscript/testscript.go
Unlike `go test`, the `testscript` command prints a blank line before either 'PASS' or 'FAIL' and its other output:
```
testscript test.txtar
PASS
```
This makes it awkward to use in a loop over many scripts, one at a time. For example:
```sh
for TS in *.txtar; do
echo -n "${TS}... "
testscript ${TS}
done
```
The desired output is:
test1.txtar... PASS
test2.txtar... PASS
...
But instead, with this leading newline, we see:
test1.txtar...
PASS
test2.txtar...
PASS
...
This commit removes the newline.
> testscript: remove leading newline before results

- testscript/doc.go
> testscript: update docs on set variables

- README.md
The linked article is the first in a forthcoming five-part user's guide to `testscript`, based on the content (from _The Power of Go: Tests_) already reviewed by our esteemed maintainers. I hope you'll consider it as a small contribution to the docs, which may help to bring in new users and contributors to the project.
> Add link to testscript tutorial

- lockedfile/internal/filelock/filelock.go
- lockedfile/internal/filelock/filelock_fcntl.go
- lockedfile/internal/filelock/filelock_other.go
- lockedfile/internal/filelock/filelock_plan9.go
- lockedfile/internal/filelock/filelock_test.go
- lockedfile/internal/filelock/filelock_unix.go
- lockedfile/internal/filelock/filelock_windows.go
- lockedfile/lockedfile.go
- lockedfile/lockedfile_filelock.go
- lockedfile/lockedfile_plan9.go
- lockedfile/lockedfile_test.go
- lockedfile/mutex.go
- lockedfile/transform_test.go
Code taken from upstream commit d7dbe0111ef2a6de80a20fef188db61d8fab5c96.
This adds a new function (`Transform`).
> lockedfile: update from Go master

- gotooltest/setup.go
- gotooltest/setup_test.go
> gotooltest: run probe commands in temporary directory

- cmd/testscript/main.go
- cmd/testscript/testdata/continue.txt
- testscript/testscript.go
> cmd/testscript: add a -continue flag to not stop at the first error

- cmd/testscript/help.go
The flag was added in #189 but not documented in the usage message.
> cmd/testscript: mention -continue flag in usage

- cmd/testscript/main.go
- testscript/testdata/testscript_logging.txt
- testscript/testscript.go
- testscript/testscript_test.go
This fixes a few issues around the existing `testscript -continue` flag. Notably:
- causing `T.Fatal` and `T.FailNow` to return normally meant that some logic inside the testscript package that was expecting the old behaviour would fail to work correctly (for example, a non-existent command would cause a panic)
- the logging logic was erroneously assuming that if we got to the end of a script, all sections had passed therefore we could omit the logged messages.
We fix the above by making "continue on error" a first class part of `testscript.Params`, so the testscript logic actually knows about it.
To test it properly, we need a couple of hacks to make the output predictable. Unfortunately, those hacks are internal only, so it's hard to add similar tests to the `cmd/testscript` command to …
> testscript: add Params.ContinueOnError

- testscript/cmd.go
- testscript/testscript.go
This uses the `-test.timeout` flag (or the `Params.Deadline` field) to send first `SIGQUIT` (to get a stack trace) and then `SIGKILL` to a stuck command. It's mostly imported from the current stdlib code, with tweaks to work around the lack of Deadline and Cleanup method access.
> testscript: import timeout behavior from stdlib

- testscript/testscript.go
- testscript/testscript_test.go
The new FailNow logic introduced in #192 had a flaw: it did not correctly handle failures in the setup code, as observed in #185.
This PR fixes that omission.
> testscript: fix error handling in setup

- .github/workflows/test.yml
- cmd/txtar-c/savedir.go
- cmd/txtar-goproxy/main.go
- cmd/txtar-x/extract.go
- fmtsort/sort.go
- go.mod
- imports/build.go
- internal/syscall/windows/registry/key.go
- modfile/read.go
- testenv/testenv.go
I noticed CI was still using Go 1.17 and 1.18.
> ci: bump Go versions

- go.mod
- go.sum
- txtar/archive.go
- txtar/archive_test.go
Although we can't quite use the x/tools/txtar implementation in its entirety (https://github.com/golang/go/issues/59264 needs to be fixed first, and we implement some other functions that x/tools/txtar doesn't (yet?) have, we can at least alias its types, which makes it possible to work with other packages that use those types.
> txtar: alias types to x/tools

- testscript/testdata/cmd_stdout_stderr.txt
- testscript/testdata/testscript_stdout_stderr_error.txt
- testscript/testscript.go
- testscript/testscript_test.go
> testscript: expose (*TestScript).stdout via Stdout()

- go.mod
- go.sum
- testscript/clonefile.go
- testscript/clonefile_darwin.go
- testscript/clonefile_other.go
- testscript/exe.go
To fix unexpected errors of type:
```
[signal: killed]
FAIL: testscripts/myecho.txt:1: unexpected command failure
```
Fixes #200
> testscript: use unix.CloneFile on MacOs 

- testscript/cmd.go
- testscript/doc.go
- testscript/envvarname.go
- testscript/envvarname_windows.go
- testscript/internal/pty/pty.go
- testscript/internal/pty/pty_darwin.go
- testscript/internal/pty/pty_linux.go
- testscript/internal/pty/pty_unsupported.go
- testscript/testdata/pty.txt
- testscript/testscript.go
- testscript/testscript_test.go
This allows testing commands that open `/dev/tty` to interact with the user separately from stdin/stdout, like age.
See https://github.com/FiloSottile/age/blob/084c974f5393e5d2776fb1bb3a35eeed271a32fa/cmd/age/testdata/terminal.txt and https://github.com/FiloSottile/age/blob/084c974f5393e5d2776fb1bb3a35eeed271a32fa/cmd/age/testdata/scrypt.txt for example scripts.
> testscript: add pty/ptyout commands

- .github/workflows/test.yml
- cmd/testscript/testdata/noproxy.txt
- go.mod
- gotooltest/testdata/cover.txt
- testscript/testdata/pty.txt
- testscript/testscript.go
(see commit messages - please do not squash)
> bump to Go 1.21, drop Go 1.19, propagate GORACE in testscript

- robustio/robustio.go
- robustio/robustio_darwin.go
- robustio/robustio_flaky.go
- robustio/robustio_other.go
- robustio/robustio_windows.go
Copied from Go commit b18b05881691861c4279a50010829150f1684fa9.
This is similar to #203 except that it addresses @mvdan's concerns:
- it comes directly from the Go repo
- it does not expose the `GetFileID` API.
> robustio: copy from cmd/go/internal/robustio

- testscript/internal/pty/pty_linux.go
Use uint32 instead of uint (64-bit in Go on s390x) to store the return value of the TIOCGPTN syscall.  This is to avoid the 32-bit value from being stored into a 64-bit buffer and get left-shifted by 32 when dereferencing, turning what should be e.g. /dev/pts/1 to /dev/pts/4294967296 on big-endian architectures such as s390x.
Special thanks to the explanation and a similar bug fix provided at https://github.com/containerd/console/pull/51
Fixes the following TestScripts/pty error on s390x:
```
=== NAME  TestScripts/pty
testscript.go:558: > [!linux] [!darwin] skip
> [darwin] skip # https://go.dev/issue/61779
> ttyin secretwords.txt
> terminalprompt
[failed to open TTY: open /dev/pts/21474836480: no such file or directory]
FAIL: testdata/pty.txt:5: unexpected command failure
```
discovered …
> testscript: fix ptyName() returning /dev/pts/4294967296 on s390x

- cmd/testscript/main.go
- dirhash/hash_test.go
- imports/scan.go
- renameio/renameio.go
- testenv/testenv_windows.go
- testscript/cmd.go
- testscript/exe.go
- testscript/testscript_test.go
- txtar/archive.go
- txtar/archive_test.go
It's been a while since io/ioutil has been deprecated.
Go 1.22 was just released, and the go.mod specifies 'go 1.20'.
This should be safe to remove at this point.
The change was largely automated, minus the `t.TempDir()` calls inside
test files, which was done manually.
> all: Move away from ioutil

- testscript/cmd.go
- testscript/testdata/custom_cd.txt
- testscript/testscript.go
- testscript/testscript_test.go
It is not currently possible for a custom testscript command
to change the working directory of that script run.
`TestScript.Exec` runs the command in a subprocess,
so one cannot do `ts.Exec("cd", dir)`.
This change adds a `Chdir` method to `TestScript`
that allows changing the working directory of the script.
The implementation is the same as the "cd" command,
which now relies on `Chdir`.
The availability of this function matches similar functionality in the
[`State.Chdir` method of rsc.io/script][1].
(I ported some tests from rsc.io/script to testscript.)
[1]: https://pkg.go.dev/rsc.io/script#State.Chdir
> testscript: Add Chdir method to change directory

- testscript/cmd.go
- testscript/doc.go
- testscript/testdata/kill.txt
- testscript/testdata/kill_unnamed.txt
This allows sending a termination signal to backgrounded commands.
Please take a look.
Closes #242
> testscript: add kill command

- .github/workflows/test.yml
- go.mod
Switches CI to run against Go 1.21 and 1.22,
and bumps the minimum required Go version to 1.21.
Dropping 1.20 isn't strictly necessary;
this is just matching prior upgrades.
It can be added back if the maintainers prefer.
> all: Add Go 1.22, drop Go 1.20

- .github/workflows/test.yml
- cmd/testscript/testdata/noproxy.txt
- go.mod
- go.sum
- testscript/testscript.go
> update dependencies and rely on Go 1.21 APIs

- cmd/testscript/main.go
- testscript/testscript.go
- testscript/testscript_test.go
The call to `T.Failed` and its associated comment are a legacy of previous implementation. The comment isn't accurate and the call isn't necessary (`FailNow` is always called even when `ContinueOnError` is set). Deprecate the associated `TFailed` type rather than removing it.
> cmd/testscript: remove redundant use of Failed

- cmd/testscript/testdata/work.txt
- testscript/testdata/big_diff.txt
- testscript/testdata/long_diff.txt
- testscript/testdata/testscript_explicit_files.txt
- testscript/testdata/testscript_logging.txt
- testscript/testdata/testscript_stdout_stderr_error.txt
- testscript/testscript.go
- testscript/testscript_test.go
This makes it possible to pass an arbitrary set of testscript files to be run instead of just a directory, making it possible for the testscript command to pass its command line arguments directly.
In order to check that all the files are actually tested, we need to make the test harness implement independent subtest failure, and it's useful to see the name of the test too so that we can see the name disambiguation logic at work, which makes for changes to some of the other tests too.
Note that the name deduping logic is somewhat improved from similar logic in cmd/testscript, in that it is always guaranteed to produce unique names even in the presence of filenames that look like deduped names.
> testscript: add Config.Files

- cmd/testscript/main.go
- cmd/testscript/testdata/error.txt
- cmd/testscript/testdata/multi.txt
- cmd/testscript/testdata/nogo.txt
- cmd/testscript/testdata/work.txt
> cmd/testscript: do not create an extra temporary directory

- testscript/testscript.go
https://github.com/codespell-project/codespell
> Fix typos discovered by codespell

- testscript/testdata/interrupt_implicit.txt
- testscript/testscript.go
(see commit message)
Fixes #228.
Fixes #260.
> testscript: ignore result when interrupting background processes

- .github/workflows/test.yml
- README.md
- go.mod
- goproxytest/proxy.go
- imports/scan.go
- internal/os/execpath/lp_unix.go
- testscript/exe.go
- testscript/testscript.go
(see commit messages - please do not squash)
> update Go, update the README

- .github/workflows/test.yml
- cache/cache.go
- cache/cache_test.go
- cmd/testscript/main.go
- cmd/txtar-addmod/addmod.go
- diff/diff.go
- fmtsort/sort.go
- fmtsort/sort_test.go
- go.mod
- goproxytest/allhex.go
- goproxytest/proxy.go
- imports/read.go
- par/work.go
- par/work_test.go
- testscript/cmd.go
- testscript/testscript.go
- testscript/testscript_test.go
> add Go 1.24.x, drop 1.22.x

- testscript/exe.go
> testscript: remove temp dirs when finishing once again

- cache/hash.go
- cache/hash_test.go
Currently the cache code, taken directly from the Go internal code, salts every hash with the current Go runtime version. This is appropriate for Go itself but not for here where the cache package is intended for more general use.
People that need the hashes to depend on the Go runtime version can explicitly include it as part of the hash.
> hash: do not salt with Go runtime version

- testscript/testdata/testscript_logging.txt
- testscript/testscript.go
> testscript: reset verbose on new blocks

- testscript/testdata/testscript_logging.txt
- testscript/testscript.go
(see commit messages - please do not squash)
> testscript: rewind last block if it was not in error

- testscript/cmd.go
> testscript: protect against no-op uses of cmp
